### ISSUE TITLE
Update the app on F-Droid

### ISSUE THREAD

**Issue by ahmadihafez** [metinkale38/prayer-times-android#150] opened 2020-02-18 09:21 UTC
The latest version on f-Droid is 2 years old and buggy, could you please update it!

**Comment by fazlerabbi37** [comment] 2020-05-03 13:43
@ahmadihafez it seems like a duplicate of #138. I would say the same as I said there, a new version has been released with `fdroid` tag in the GitHub on Apr 19, 2020. The F-Droid metadata has been updated [here](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.metinkale.prayer.yml). It will take some time to for F-Droid to build it, so we need to be patience a bit.

---

also, to keep things a bit more organized and less confusing for others users, I think it would be really appreciated if we track the issue in #138 and colse this one.

**Closed** 2020-05-04 15:54 UTC
Labels: duplicate
